vich_uploader:
    db_driver: orm

    mappings:
        docs_image:
            uri_prefix: /uploads/docs
            upload_destination: '%kernel.project_dir%/public/uploads/docs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        depots_image:
            uri_prefix: /uploads/depots
            upload_destination: '%kernel.project_dir%/public/uploads/depots'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        depots_fichiers:
            uri_prefix: /uploads/depots
            upload_destination: '%kernel.project_dir%/public/uploads/depots'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true